//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        public aluno()
        {
            this.pontuacao = new HashSet<pontuacao>();
            this.resultado = new HashSet<resultado>();
            this.permissao = new HashSet<permissao>();
        }
    
        public int idAluno { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> Turma_id { get; set; }
    
        public virtual ICollection<pontuacao> pontuacao { get; set; }
        public virtual ICollection<resultado> resultado { get; set; }
        public virtual turma turma { get; set; }
        public virtual ICollection<permissao> permissao { get; set; }
    }
}
