//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicacao
    {
        public int idAplicacao { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Turma_id { get; set; }
        public Nullable<int> Questionario_id { get; set; }
        public Nullable<int> Evento_id { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual questionario questionario { get; set; }
        public virtual turma turma { get; set; }
    }
}
