//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public area()
        {
            this.questao = new HashSet<questao>();
        }
    
        public int idArea { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Disciplina_id { get; set; }
    
        public virtual disciplina disciplina { get; set; }
        public virtual ICollection<questao> questao { get; set; }
    }
}
