//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class arquivo
    {
        public arquivo()
        {
            this.itemarquivo = new HashSet<itemarquivo>();
            this.questionario = new HashSet<questionario>();
        }
    
        public int idArquivo { get; set; }
        public string Nome { get; set; }
        public string NomeFisico { get; set; }
        public string Extensao { get; set; }
        public Nullable<int> TipoArquivo_id { get; set; }
    
        public virtual tipoarquivo tipoarquivo { get; set; }
        public virtual ICollection<itemarquivo> itemarquivo { get; set; }
        public virtual ICollection<questionario> questionario { get; set; }
    }
}
