//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplina
    {
        public disciplina()
        {
            this.area = new HashSet<area>();
            this.questao = new HashSet<questao>();
            this.resultado = new HashSet<resultado>();
        }
    
        public int idDisciplina { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<area> area { get; set; }
        public virtual ICollection<questao> questao { get; set; }
        public virtual ICollection<resultado> resultado { get; set; }
    }
}
