//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class instituicao
    {
        public instituicao()
        {
            this.evento = new HashSet<evento>();
            this.permissao = new HashSet<permissao>();
            this.turma = new HashSet<turma>();
        }
    
        public int idInstituicao { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<evento> evento { get; set; }
        public virtual ICollection<permissao> permissao { get; set; }
        public virtual ICollection<turma> turma { get; set; }
    }
}
