//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemquestao
    {
        public itemquestao()
        {
            this.itemarquivo = new HashSet<itemarquivo>();
            this.salto = new HashSet<salto>();
        }
    
        public int idItemQuestao { get; set; }
        public string Titulo { get; set; }
        public Nullable<bool> OpcaoCorreta { get; set; }
        public Nullable<bool> TransformaImagem { get; set; }
        public Nullable<bool> EPergunta { get; set; }
        public Nullable<bool> EResposta { get; set; }
        public Nullable<bool> ETentativa { get; set; }
        public Nullable<int> OrdemTela { get; set; }
        public Nullable<int> OrdemResposta { get; set; }
        public Nullable<bool> ContemAudio { get; set; }
        public Nullable<int> idBase { get; set; }
        public Nullable<int> TipoItem_id { get; set; }
        public Nullable<int> Questao_id { get; set; }
    
        public virtual ICollection<itemarquivo> itemarquivo { get; set; }
        public virtual questao questao { get; set; }
        public virtual tipoitem tipoitem { get; set; }
        public virtual ICollection<salto> salto { get; set; }
    }
}
