//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class corujadbEntities : DbContext
    {
        public corujadbEntities()
            : base("name=corujadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aluno> aluno { get; set; }
        public DbSet<aplicacao> aplicacao { get; set; }
        public DbSet<area> area { get; set; }
        public DbSet<arquivo> arquivo { get; set; }
        public DbSet<disciplina> disciplina { get; set; }
        public DbSet<evento> evento { get; set; }
        public DbSet<instituicao> instituicao { get; set; }
        public DbSet<itemarquivo> itemarquivo { get; set; }
        public DbSet<itemquestao> itemquestao { get; set; }
        public DbSet<nivel> nivel { get; set; }
        public DbSet<papel> papel { get; set; }
        public DbSet<permissao> permissao { get; set; }
        public DbSet<pontuacao> pontuacao { get; set; }
        public DbSet<questao> questao { get; set; }
        public DbSet<questionario> questionario { get; set; }
        public DbSet<resultado> resultado { get; set; }
        public DbSet<salto> salto { get; set; }
        public DbSet<tipoarquivo> tipoarquivo { get; set; }
        public DbSet<tipoitem> tipoitem { get; set; }
        public DbSet<tipoquestao> tipoquestao { get; set; }
        public DbSet<turma> turma { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
