//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel
    {
        public nivel()
        {
            this.questionario = new HashSet<questionario>();
            this.turma = new HashSet<turma>();
        }
    
        public int idNivel { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<questionario> questionario { get; set; }
        public virtual ICollection<turma> turma { get; set; }
    }
}
