//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class papel
    {
        public papel()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int idPapel { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
