//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissao
    {
        public int idPermissao { get; set; }
        public Nullable<int> Usuario_id { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public Nullable<int> Aluno_id { get; set; }
        public Nullable<int> Turma_id { get; set; }
        public Nullable<int> Instituicao_id { get; set; }
    
        public virtual aluno aluno { get; set; }
        public virtual instituicao instituicao { get; set; }
        public virtual turma turma { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
