//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class pontuacao
    {
        public int Aluno_idAluno { get; set; }
        public int Questao_idQuestao { get; set; }
        public Nullable<bool> Acertou { get; set; }
        public Nullable<int> Tentativas { get; set; }
        public Nullable<double> Tempo { get; set; }
        public string Mouse { get; set; }
        public string Clicks { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
    
        public virtual aluno aluno { get; set; }
        public virtual questao questao { get; set; }
    }
}
