//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionario
    {
        public questionario()
        {
            this.aplicacao = new HashSet<aplicacao>();
            this.questao = new HashSet<questao>();
            this.resultado = new HashSet<resultado>();
        }
    
        public int idQuestionario { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Cor { get; set; }
        public Nullable<bool> RepetePergunta { get; set; }
        public Nullable<int> idBase { get; set; }
        public Nullable<int> Nivel_id { get; set; }
        public Nullable<int> Arquivo_id { get; set; }
    
        public virtual ICollection<aplicacao> aplicacao { get; set; }
        public virtual arquivo arquivo { get; set; }
        public virtual nivel nivel { get; set; }
        public virtual ICollection<questao> questao { get; set; }
        public virtual ICollection<resultado> resultado { get; set; }
    }
}
