//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoarquivo
    {
        public tipoarquivo()
        {
            this.arquivo = new HashSet<arquivo>();
        }
    
        public int idTipoArquivo { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<arquivo> arquivo { get; set; }
    }
}
