//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class turma
    {
        public turma()
        {
            this.aluno = new HashSet<aluno>();
            this.aplicacao = new HashSet<aplicacao>();
            this.permissao = new HashSet<permissao>();
        }
    
        public int idTurma { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Instituicao_id { get; set; }
        public Nullable<int> Nivel_id { get; set; }
    
        public virtual ICollection<aluno> aluno { get; set; }
        public virtual ICollection<aplicacao> aplicacao { get; set; }
        public virtual instituicao instituicao { get; set; }
        public virtual nivel nivel { get; set; }
        public virtual ICollection<permissao> permissao { get; set; }
    }
}
